
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouziggoadbukuvfgrrgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91emlnZ29hZGJ1a3V2ZmdycmdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MTc0MjUsImV4cCI6MjA2NzE5MzQyNX0.MlUFz9oC1NnOIWzc6Bc6aSUZY3KnkgaGMTJSjA4C6Jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
